/*
 * 本地化存储(localStorage) 组件
 * 版权所有(C) 2013 马超 (zjcn5205@yeah.net)
 */
/* eslint-disable */
(function(g){var h,noop=function(){},document=g.document,notSupport={set:noop,get:noop,remove:noop,clear:noop,each:noop,obj:noop,length:0};(function(){if("localStorage"in g){try{h=g.localStorage;return}catch(e){}}var o=document.getElementsByTagName("head")[0],hostKey=g.location.hostname||"localStorage",d=new Date(),doc,agent;if(!o.addBehavior){try{h=g.localStorage}catch(e){h=null}return}try{agent=new ActiveXObject('htmlfile');agent.open();agent.write('<s'+'cript>document.w=window;</s'+'cript><iframe src="/favicon.ico"></iframe>');agent.close();doc=agent.w.frames[0].document;o=doc.createElement('head');doc.appendChild(o)}catch(e){o=document.getElementsByTagName("head")[0]}try{d.setDate(d.getDate()+36500);o.addBehavior("#default#userData");o.expires=d.toUTCString();o.load(hostKey);o.save(hostKey)}catch(e){return}var c,attrs;try{c=o.XMLDocument.documentElement;attrs=c.attributes}catch(e){return}var f="p__hack_",spfix="m-_-c",reg1=new RegExp("^"+f),reg2=new RegExp(spfix,"g"),encode=function(a){return encodeURIComponent(f+a).replace(/%/g,spfix)},decode=function(a){return decodeURIComponent(a.replace(reg2,"%")).replace(reg1,"")};h={length:attrs.length,isVirtualObject:true,getItem:function(a){return(attrs.getNamedItem(encode(a))||{nodeValue:null}).nodeValue||c.getAttribute(encode(a))},setItem:function(a,b){try{c.setAttribute(encode(a),b);o.save(hostKey);this.length=attrs.length}catch(e){}},removeItem:function(a){try{c.removeAttribute(encode(a));o.save(hostKey);this.length=attrs.length}catch(e){}},clear:function(){while(attrs.length){this.removeItem(attrs[0].nodeName)}this.length=0},key:function(i){return attrs[i]?decode(attrs[i].nodeName):undefined}};if(!("localStorage"in g))g.localStorage=h})();g.LS=!h?notSupport:{set:function(a,b){if(this.get(a)!==undefined)this.remove(a);h.setItem(a,b);this.length=h.length},get:function(a){var v=h.getItem(a);return v===null?undefined:v},remove:function(a){h.removeItem(a);this.length=h.length},clear:function(){h.clear();this.length=0},each:function(a){var b=this.obj(),fn=a||function(){},key;for(key in b)if(fn.call(this,key,this.get(key))===false)break},obj:function(){var a={},i=0,n,key;if(h.isVirtualObject){a=h.key(-1)}else{n=h.length;for(;i<n;i++){key=h.key(i);a[key]=this.get(key)}}return a},length:h.length};if(g.jQuery)g.jQuery.LS=g.LS})(window);
//导出接口
define([], function(){
  return window.LS
});
